---
# Source: ks-core/templates/extension-museum.yaml
apiVersion: v1
kind: Secret
metadata:
  name: extensions-museum-certs
  namespace: kubesphere-system
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIakNDQWdhZ0F3SUJBZ0lSQUtzN083c3AxZTZsdVVYU3ZKV051WEV3RFFZSktvWklodmNOQVFFTEJRQXcKR1RFWE1CVUdBMVVFQXhNT2MyVnNaaTF6YVdkdVpXUXRZMkV3SGhjTk1qVXdNekl3TURZek1EQTFXaGNOTXpVdwpNekU0TURZek1EQTFXakFaTVJjd0ZRWURWUVFERXc1elpXeG1MWE5wWjI1bFpDMWpZVENDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkdDMUNqOGpXSnVhRDY3NGJmRTZGS0g1dWJvTnBTamVxaDYKQlNocThMTTMrcWwwMkNSdGpMeEdpQm10eHN6TVRnS21NZHV5NVB0eXF1aGRyYUtqYkpYQk82YzVxY2VnYjN2SQpRVSs5R1BNUXY3WGhMUHFpdzIveUY1aXZUZUpSeVBhZVgrK0VVOGFJalg2NENXdFRlUkQycksvTGhDTnNHa1RzCnp6QkFJbk1qUGpBaDZGczBpQVh4dzRTRDJPTHFveHE1WFMrUlMrdENFUnZsZGd1cG5TRldGV1A1OURiMys3bVUKMHhVYWNsZVFKMXZKTHl1WU8vUi9WOUJaS1FNdGRaZm0xRW05Vzl4V1J2eUNFVEVJbEpFR3BTejRFYTg0ekptbQowa2h1TS9NemRaT21MWjhjSVd5TDVkcXVoKzduN21HSlJSQnZSZkdITFhxQy85UTB3OGtDQXdFQUFhTmhNRjh3CkRnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlJhM2Rjbkg1MU5aV0Ixeks2cmJ3clZiOHAxd2pBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFoL2luNUo3MEtlZHFZZWtFbmpPc3pneDk0TUkvN2k2eTJHVTA3SFMzCllFZXZkd25NZHlnWEgrNHNVb2huc1FNd01wTk02Z2lCWk5SWmQyU0lLazRob0t1cDZyQnI3WTY0ZVl5Q0tHNEUKblVZNmZEenZWd3hlV1EvbjZRRVpmWS9lbFpNRmtNODFueUN5MTI1UkM3cGNhUWc2Wm1BbU41R1d0aW5VNkttYwp6YSszZ21sZUE2N0RHaFlTaDdoeVMvWGkyODZ0aHR5WXIybUNCY1ZFOVRlTEpyQ1YzWHpKOFFCYWtGamtWODJSCk5lb3R4M0JLckQ0dmlKcUxCVktjQldMVUF5MUxBemZzWWZIRWU4WXZpL0pOSmVPMHp1ZCtCMEp4eEtUMjd0YWYKa05QMTF2cS9xMzQzR1RtcnMrc3gxVlNWL0RHZkIxejRFVFk3L0dRM243MlljUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnekNDQW11Z0F3SUJBZ0lSQUt6VGFudCtXa2ZBcktuTDBoVDFvOHd3RFFZSktvWklodmNOQVFFTEJRQXcKR1RFWE1CVUdBMVVFQXhNT2MyVnNaaTF6YVdkdVpXUXRZMkV3SGhjTk1qVXdNekl3TURZek1EQTFXaGNOTXpVdwpNekU0TURZek1EQTFXakFrTVNJd0lBWURWUVFERXhscmN5MWpiM0psTFdWNGRHVnVjMmx2Ym5NdGJYVnpaWFZ0Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMUpqWlhOZlpLUDJ2OFZvMXpJcTQKOC9lOFBLTXFzYVhmaWQzbTFBdDg0YWlSRkUyS1BwZVY2b1QrUXlMZDV2ZkZwTWNOTFl4K2d4VUcrV01VRVEzUQpYOXpEZUQ1SkpaRFkxTHpsWThDbi9qKytNaFV5L1NWWjNPSlM2eFF0a0VlNmN4Qys4UFZiTGJXQ0tkWlJGaFoxCmpZVGhGUFppRmtzUXJyVEFYY0ZoYnEyYUUrRGJ1aCt1MVdLTUJnSWw0aTl2aHk2cU81blU3ZEQzcDkrOWNYODAKaHRpVTFkQ0FOdlZONEIzSERzeUZDUmk0WGI2cEZGaGZ3akQ1dnhKWCtpWEh1WHQxVHRRL2w4akNhN3FRL1hybgozOTYyaWpON3pGQUVVa3JOZGdVNTAvTFpoSlMxODdBSVFkL3ZDeURaMDh5STZpQXpkTjNpcGtUUnRFNS9qcTA4ClRRSURBUUFCbzRHNk1JRzNNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0QKQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSYTNkY25INTFOWldCMQp6SzZyYndyVmI4cDF3akJYQmdOVkhSRUVVREJPZ2lObGVIUmxibk5wYjI1ekxXMTFjMlYxYlM1cmRXSmxjM0JvClpYSmxMWE41YzNSbGJZSW5aWGgwWlc1emFXOXVjeTF0ZFhObGRXMHVhM1ZpWlhOd2FHVnlaUzF6ZVhOMFpXMHUKYzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1VWWGNvUDd3VjdRUGhWOEFKay90Z3lSVElzMzFmU3ZmSAprWVF2TXp1cHJUR3ZuQVpWeGRtWGZFV0UzV2Z4amdvUHlodjJFTUdjeU9wWHdBUEZEVW5sRTQ0bFdxZ1VUS280CmkxY256aFRtTDZZWXhDUVo0YzRLMjZPSmtwV1hFeG5sdG4vbVQwNE9rMHJmQnpGTFkyVDhrY1g0VTZ1NEhsUWkKNFpjd1ZVOTg3eHhrbWRLTldGSTR0by9hYW41TDdFVklwT1VNZGRZcVY2N28xZ3Y0RDRQSlV0Y2xFblFLZ2p0SQpMbFNJWGE2WWNqUUZZRUdDMUxSdFlHQlU2TmQ5cVpSV2VqY3FSb0dRV0h2cWFPK0FuWUZyNmVLL0dxbmJpM2FDCmJ1OW5EN3Y4eTk0WXpZeVFJZHhVOE01Qk1ZNW4yMSs4ZnQ1TXZQMitDRTBlazRWRCtBZjQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMUpqWlhOZlpLUDJ2OFZvMXpJcTQ4L2U4UEtNcXNhWGZpZDNtMUF0ODRhaVJGRTJLClBwZVY2b1QrUXlMZDV2ZkZwTWNOTFl4K2d4VUcrV01VRVEzUVg5ekRlRDVKSlpEWTFMemxZOENuL2orK01oVXkKL1NWWjNPSlM2eFF0a0VlNmN4Qys4UFZiTGJXQ0tkWlJGaFoxallUaEZQWmlGa3NRcnJUQVhjRmhicTJhRStEYgp1aCt1MVdLTUJnSWw0aTl2aHk2cU81blU3ZEQzcDkrOWNYODBodGlVMWRDQU52Vk40QjNIRHN5RkNSaTRYYjZwCkZGaGZ3akQ1dnhKWCtpWEh1WHQxVHRRL2w4akNhN3FRL1hybjM5NjJpak43ekZBRVVrck5kZ1U1MC9MWmhKUzEKODdBSVFkL3ZDeURaMDh5STZpQXpkTjNpcGtUUnRFNS9qcTA4VFFJREFRQUJBb0lCQUF3WXVsMTNCcXMzYkJodQppcHNkMVpKRUtWakY2L3I1dGpOeEJkNVEzUVUyQXpORmlqVXZpTjgwUEFkejUyNXA4THdFZTNKNUNRWEtYNEEzCkxBQWdhaGZhUnVFRG9rUFo3d3lEeHdXYkE3UUt5bmF0RUI2cFRtaXNGQTIrTXkxL2QxTnV3MzZRWjJTOWJDK1gKT3p2bmdUN1JMY0YwbDNZdlJUNjdtQ3A5ZzE2NXRWNFdiWDN2NGhPbWJTR3kwdlpFNXdmaTBTbXYyeGMvaWhpLwoxRm5DeXhlRmdZcG9vblJENDV5SXFHakluUms1Z0gvZHRkMWtHZXlvWS9qQTRJWFFtNEcyU3d6TitSOTNoL0hJCjh3TWZxNkpXYVd4bWIrbXJHbFJrNGFabDdaZUF3VUtVWGdvdEJXT01zNVU3OG8vQ2V4WjByMXcycW5PbllyYUkKYVRHTUpBRUNnWUVBMUt0SHJoa3o3VmJqMzBtTHJwUWFKNnoycnMvaE4rUUd3bUJtRGpPaWs1cWxiL0VRWlFROAo1bnpxTW5NL2wzNFJhU21tVXRtMWRZSnRXek5xeFlzUGhoZlM5OUJQTDJwNmExRjRNZ1FRUGgwdFF3YXdEYUFpCjlZNi9PZHZUODJFZGorakNmSXpzL3NvRmV0eWRWZjI5MUV4Y3hsVzB6N2tGSUVHNmk5ODZsVTBDZ1lFQS8rblEKVlgxbkRXSzVxVG4xeEx5d2V2R0FlVzM4UUFKRGZhK3hXbzNtTG1RWG5Gb3pUKzNXOWtwRFBLS2V0M1VFMjEwaQpUMG5QaEVBRVlmeEF0clB2WUxWZjhUdTRmT1BmZ2xUQjNycWZaMS9WR1BuUEQvbmFpZ2J5TlB0YzNvekNiTHd1CmN1VE5Gd1djbHcrVmxaRjQyY0xJTFFJd0dXMDV3NU82V0w0ZHd3RUNnWUVBaUNOeENta0Z6YndldVZSYVA1SjkKUDhMQVUxMnR2ZHFSM1NKYWttTEpneFd2Sy82MFVRWXFlaDJpeWxMdWRXcjFlRTE2TkhVN2JSTG1NRWkwNCtwRwpNTC9WaEYvc0lOMVhxcFdIalBUKzlOUTJvajZJdXVBMUlONlZXVk40MWNib1pyUklzL1IremdmREJFaHZ5NWxZClNLdnRnK1ZmanMzUkV6b2dVZU8vbTgwQ2dZQTYyS3NkWFc2Njl6NjJHU3ZZaDRNVllqOG1yUkhhTGlzUzFibTAKbHZpZEprci9td1k5bFBWZlFRaGhBd3Y0SjZKc1J1aEN6emcyc3ZuUEJsQmpNdEVTcmVKWCtHR2Q1bEJaQ2VCaQp0UXMrbkJ6R1Yzc3pzMEo3aHNsZlFZWERieDZ1SGorWUQrRFJNR3NubVYvT090dE5SNnI4SG9xczdoN2dTRElMCmdmd2FBUUtCZ0NKdXJxQUMycUhpQnF3S3U3Y3pyL0NQb3lFcXI2VHVRRlFaZWE2S3BSbTRFcTNzbEVLUzBLYmwKaUFYVGlMYlgvRE9JTzBEbGUyNjl3OWdPWG1mUG9lMkVrSnZuSjlVM3BtZXBrd2p1Ukp4T1YvZzJnZENUNEVJYwo4Q2xQOVNFeVdIMkZBUlVzbm9YVFl6ZGxkS082a1NpTFpGZk9JaWlieHZpblVVSUtyUDloCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: ks-core/templates/extension-museum.yaml
apiVersion: v1
kind: Service
metadata:
  name: extensions-museum
  namespace: kubesphere-system
spec:
  selector:
    app: extensions-museum
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
---
# Source: ks-core/templates/extension-museum.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extensions-museum
  namespace: kubesphere-system
  labels:
    app: extensions-museum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extensions-museum
  template:
    metadata:
      labels:
        app: extensions-museum
    spec:
      containers:
        - name: extensions-museum
          image: docker.io/kubesphere/ks-extensions-museum:latest
          command:
            - "/chartmuseum"
            - "--storage-local-rootdir"
            - "/charts"
            - "--storage"
            - "local"
            - "--tls-cert"
            - "/etc/certs/tls.crt"
            - "--tls-key"
            - "/etc/certs/tls.key"
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: certs
              mountPath: /etc/certs/
      volumes:
        - name: certs
          secret:
            secretName: extensions-museum-certs
---
# Source: ks-core/templates/extension-museum.yaml
apiVersion: kubesphere.io/v1alpha1
kind: Repository
metadata:
  name: extensions-museum
spec:
  url: https://extensions-museum.kubesphere-system.svc
  insecure: true
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIakNDQWdhZ0F3SUJBZ0lSQUtzN083c3AxZTZsdVVYU3ZKV051WEV3RFFZSktvWklodmNOQVFFTEJRQXcKR1RFWE1CVUdBMVVFQXhNT2MyVnNaaTF6YVdkdVpXUXRZMkV3SGhjTk1qVXdNekl3TURZek1EQTFXaGNOTXpVdwpNekU0TURZek1EQTFXakFaTVJjd0ZRWURWUVFERXc1elpXeG1MWE5wWjI1bFpDMWpZVENDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkdDMUNqOGpXSnVhRDY3NGJmRTZGS0g1dWJvTnBTamVxaDYKQlNocThMTTMrcWwwMkNSdGpMeEdpQm10eHN6TVRnS21NZHV5NVB0eXF1aGRyYUtqYkpYQk82YzVxY2VnYjN2SQpRVSs5R1BNUXY3WGhMUHFpdzIveUY1aXZUZUpSeVBhZVgrK0VVOGFJalg2NENXdFRlUkQycksvTGhDTnNHa1RzCnp6QkFJbk1qUGpBaDZGczBpQVh4dzRTRDJPTHFveHE1WFMrUlMrdENFUnZsZGd1cG5TRldGV1A1OURiMys3bVUKMHhVYWNsZVFKMXZKTHl1WU8vUi9WOUJaS1FNdGRaZm0xRW05Vzl4V1J2eUNFVEVJbEpFR3BTejRFYTg0ekptbQowa2h1TS9NemRaT21MWjhjSVd5TDVkcXVoKzduN21HSlJSQnZSZkdITFhxQy85UTB3OGtDQXdFQUFhTmhNRjh3CkRnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlJhM2Rjbkg1MU5aV0Ixeks2cmJ3clZiOHAxd2pBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFoL2luNUo3MEtlZHFZZWtFbmpPc3pneDk0TUkvN2k2eTJHVTA3SFMzCllFZXZkd25NZHlnWEgrNHNVb2huc1FNd01wTk02Z2lCWk5SWmQyU0lLazRob0t1cDZyQnI3WTY0ZVl5Q0tHNEUKblVZNmZEenZWd3hlV1EvbjZRRVpmWS9lbFpNRmtNODFueUN5MTI1UkM3cGNhUWc2Wm1BbU41R1d0aW5VNkttYwp6YSszZ21sZUE2N0RHaFlTaDdoeVMvWGkyODZ0aHR5WXIybUNCY1ZFOVRlTEpyQ1YzWHpKOFFCYWtGamtWODJSCk5lb3R4M0JLckQ0dmlKcUxCVktjQldMVUF5MUxBemZzWWZIRWU4WXZpL0pOSmVPMHp1ZCtCMEp4eEtUMjd0YWYKa05QMTF2cS9xMzQzR1RtcnMrc3gxVlNWL0RHZkIxejRFVFk3L0dRM243MlljUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
status:
  lastSyncTime: null
