---
# Source: ks-core/templates/platformconfig-telemetry.yaml
apiVersion: v1
kind: Secret
metadata:
  name: io.kubesphere.config.platformconfig.telemetry
  namespace: kubesphere-system
type: config.kubesphere.io/generic-platform-config
stringData:
  configuration.yaml: |
    enabled: false
    endpoint: "https://kubesphere.cloud"
